version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - dockernet
    ports:
      - 3305:3306

  app:
    build: 
      context: .
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s ./fresh_market
    networks:
      - dockernet
    tty: true
    depends_on:
      - db
    ports:
      - 8080:8080

networks:
  dockernet:
    driver: bridge