// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/natpapa17/MercadoFresco-ASociedadeGo/internal/buyers/domain"
	mock "github.com/stretchr/testify/mock"
)

// BuyerRepository is an autogenerated mock type for the BuyerRepository type
type BuyerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: firstName, lastName, address, document
func (_m *BuyerRepository) Create(firstName string, lastName string, address string, document string) (domain.Buyer, error) {
	ret := _m.Called(firstName, lastName, address, document)

	var r0 domain.Buyer
	if rf, ok := ret.Get(0).(func(string, string, string, string) domain.Buyer); ok {
		r0 = rf(firstName, lastName, address, document)
	} else {
		r0 = ret.Get(0).(domain.Buyer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = rf(firstName, lastName, address, document)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBuyerById provides a mock function with given fields: id
func (_m *BuyerRepository) DeleteBuyerById(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *BuyerRepository) GetAll() (domain.Buyers, error) {
	ret := _m.Called()

	var r0 domain.Buyers
	if rf, ok := ret.Get(0).(func() domain.Buyers); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Buyers)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBuyerById provides a mock function with given fields: id
func (_m *BuyerRepository) GetBuyerById(id int) (domain.Buyer, error) {
	ret := _m.Called(id)

	var r0 domain.Buyer
	if rf, ok := ret.Get(0).(func(int) domain.Buyer); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Buyer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBuyerById provides a mock function with given fields: id, firstName, lastName, address, document
func (_m *BuyerRepository) UpdateBuyerById(id int, firstName string, lastName string, address string, document string) (domain.Buyer, error) {
	ret := _m.Called(id, firstName, lastName, address, document)

	var r0 domain.Buyer
	if rf, ok := ret.Get(0).(func(int, string, string, string, string) domain.Buyer); ok {
		r0 = rf(id, firstName, lastName, address, document)
	} else {
		r0 = ret.Get(0).(domain.Buyer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string, string, string, string) error); ok {
		r1 = rf(id, firstName, lastName, address, document)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBuyerRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewBuyerRepository creates a new instance of BuyerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBuyerRepository(t mockConstructorTestingTNewBuyerRepository) *BuyerRepository {
	mock := &BuyerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
