// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	employee "github.com/natpapa17/MercadoFresco-ASociedadeGo/internal/employee"
	mock "github.com/stretchr/testify/mock"
)

// WareHouseRepository is an autogenerated mock type for the WareHouseRepository type
type WareHouseRepository struct {
	mock.Mock
}

// GetById provides a mock function with given fields: id
func (_m *WareHouseRepository) GetById(id int) (employee.Warehouse, error) {
	ret := _m.Called(id)

	var r0 employee.Warehouse
	if rf, ok := ret.Get(0).(func(int) employee.Warehouse); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(employee.Warehouse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewWareHouseRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewWareHouseRepository creates a new instance of WareHouseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWareHouseRepository(t mockConstructorTestingTNewWareHouseRepository) *WareHouseRepository {
	mock := &WareHouseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
