// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	buyers "github.com/natpapa17/MercadoFresco-ASociedadeGo/internal/buyers"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: firstName, lastName, address, document
func (_m *Service) Create(firstName string, lastName string, address string, document string) (buyers.Buyer, error) {
	ret := _m.Called(firstName, lastName, address, document)

	var r0 buyers.Buyer
	if rf, ok := ret.Get(0).(func(string, string, string, string) buyers.Buyer); ok {
		r0 = rf(firstName, lastName, address, document)
	} else {
		r0 = ret.Get(0).(buyers.Buyer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = rf(firstName, lastName, address, document)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *Service) DeleteBuyerById(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *Service) GetAll() ([]buyers.Buyer, error) {
	ret := _m.Called()

	var r0 []buyers.Buyer
	if rf, ok := ret.Get(0).(func() []buyers.Buyer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]buyers.Buyer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *Service) GetBuyerById(id int) (buyers.Buyer, error) {
	ret := _m.Called(id)

	var r0 buyers.Buyer
	if rf, ok := ret.Get(0).(func(int) buyers.Buyer); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(buyers.Buyer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateById provides a mock function with given fields: id, firstName, lastName, address, document
func (_m *Service) UpdateBuyerById(id int, firstName string, lastName string, address string, document string) (buyers.Buyer, error) {
	ret := _m.Called(id, firstName, lastName, address, document)

	var r0 buyers.Buyer
	if rf, ok := ret.Get(0).(func(int, string, string, string, string) buyers.Buyer); ok {
		r0 = rf(id, firstName, lastName, address, document)
	} else {
		r0 = ret.Get(0).(buyers.Buyer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string, string, string, string) error); ok {
		r1 = rf(id, firstName, lastName, address, document)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
