// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	domain "github.com/natpapa17/MercadoFresco-ASociedadeGo/internal/carriers/domain"
	mock "github.com/stretchr/testify/mock"
)

// CarrierService is an autogenerated mock type for the CarrierService type
type CarrierService struct {
	mock.Mock
}

// Create provides a mock function with given fields: cid, companyName, address, telephone, localityId
func (_m *CarrierService) Create(cid string, companyName string, address string, telephone string, localityId int) (domain.Carrier, error) {
	ret := _m.Called(cid, companyName, address, telephone, localityId)

	var r0 domain.Carrier
	if rf, ok := ret.Get(0).(func(string, string, string, string, int) domain.Carrier); ok {
		r0 = rf(cid, companyName, address, telephone, localityId)
	} else {
		r0 = ret.Get(0).(domain.Carrier)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string, int) error); ok {
		r1 = rf(cid, companyName, address, telephone, localityId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllNumberOfCarriersPerLocality provides a mock function with given fields:
func (_m *CarrierService) GetAllNumberOfCarriersPerLocality() (domain.ReportsNumberOfCarriersPerLocality, error) {
	ret := _m.Called()

	var r0 domain.ReportsNumberOfCarriersPerLocality
	if rf, ok := ret.Get(0).(func() domain.ReportsNumberOfCarriersPerLocality); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.ReportsNumberOfCarriersPerLocality)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNumberOfCarriersPerLocalities provides a mock function with given fields: localitiesIds
func (_m *CarrierService) GetNumberOfCarriersPerLocalities(localitiesIds []int) (domain.ReportsNumberOfCarriersPerLocality, error) {
	ret := _m.Called(localitiesIds)

	var r0 domain.ReportsNumberOfCarriersPerLocality
	if rf, ok := ret.Get(0).(func([]int) domain.ReportsNumberOfCarriersPerLocality); ok {
		r0 = rf(localitiesIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.ReportsNumberOfCarriersPerLocality)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]int) error); ok {
		r1 = rf(localitiesIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCarrierService interface {
	mock.TestingT
	Cleanup(func())
}

// NewCarrierService creates a new instance of CarrierService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCarrierService(t mockConstructorTestingTNewCarrierService) *CarrierService {
	mock := &CarrierService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
