-- MySQL Script generated by MySQL Workbench
-- Tue Jul  5 11:00:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fresh_market
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fresh_market
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fresh_market` DEFAULT CHARACTER SET utf8 ;
USE `fresh_market` ;

-- -----------------------------------------------------
-- Table `fresh_market`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Countries` (
  `id` INT NOT NULL,
  `country_name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Provinces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Provinces` (
  `id` INT NOT NULL,
  `province_name` VARCHAR(255) NULL,
  `Countries_id` INT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_Provinces_Countries1_idx` (`Countries_id` ASC),
  CONSTRAINT `fk_Provinces_Countries1`
    FOREIGN KEY (`Countries_id`)
    REFERENCES `fresh_market`.`Countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Locaities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Locaities` (
  `id` INT NOT NULL,
  `loality_name` VARCHAR(255) NULL,
  `Provinces_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Locaities_Provinces1_idx` (`Provinces_id` ASC),
  CONSTRAINT `fk_Locaities_Provinces1`
    FOREIGN KEY (`Provinces_id`)
    REFERENCES `fresh_market`.`Provinces` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Seller` (
  `id` INT NOT NULL,
  `cid` VARCHAR(255) NOT NULL,
  `company_name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(255) NOT NULL,
  `Locaities_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Seller_Locaities1_idx` (`Locaities_id` ASC),
  CONSTRAINT `fk_Seller_Locaities1`
    FOREIGN KEY (`Locaities_id`)
    REFERENCES `fresh_market`.`Locaities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Products_Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Products_Types` (
  `id` INT NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Product` (
  `id` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `Expiration_rate` DECIMAL(19,2) NOT NULL,
  `freezing_rate` DECIMAL(19,2) NOT NULL,
  `heigth` DECIMAL(19,2) NOT NULL,
  `lenght` DECIMAL(19,2) NOT NULL,
  `net_weight` DECIMAL(19,2) NOT NULL,
  `product_code` VARCHAR(255) NOT NULL,
  `recommended_freezing_temperature` DECIMAL(19,2) NOT NULL,
  `width` DECIMAL(19,2) NOT NULL,
  `Seller_id` INT NULL,
  `Products_Types_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Product_Seller1_idx` (`Seller_id` ASC),
  INDEX `fk_Product_Products_Types1_idx` (`Products_Types_id` ASC),
  UNIQUE INDEX `Products_Types_id_UNIQUE` (`Products_Types_id` ASC),
  CONSTRAINT `fk_Product_Seller1`
    FOREIGN KEY (`Seller_id`)
    REFERENCES `fresh_market`.`Seller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Products_Types1`
    FOREIGN KEY (`Products_Types_id`)
    REFERENCES `fresh_market`.`Products_Types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Warehouse` (
  `id` INT NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(255) NOT NULL,
  `warehouse_code` VARCHAR(255) NOT NULL,
  `Locaities_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Warehouse_Locaities1_idx` (`Locaities_id` ASC),
  CONSTRAINT `fk_Warehouse_Locaities1`
    FOREIGN KEY (`Locaities_id`)
    REFERENCES `fresh_market`.`Locaities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Section` (
  `id` INT NOT NULL,
  `section_number` VARCHAR(255) NULL,
  `current_capacity` INT NULL,
  `current_temperature` DECIMAL(19,2) NULL,
  `maximum_capacity` INT NULL,
  `minimum_capacity` INT NULL,
  `minimum_temperature` DECIMAL(19,2) NULL,
  `Products_Types_id` INT NULL,
  `Warehouse_id` INT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_Section_Products_Types1_idx` (`Products_Types_id` ASC),
  INDEX `fk_Section_Warehouse1_idx` (`Warehouse_id` ASC),
  CONSTRAINT `fk_Section_Products_Types1`
    FOREIGN KEY (`Products_Types_id`)
    REFERENCES `fresh_market`.`Products_Types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Section_Warehouse1`
    FOREIGN KEY (`Warehouse_id`)
    REFERENCES `fresh_market`.`Warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Employees` (
  `id` INT NOT NULL,
  `id_card_number` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `Warehouse_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Employees_Warehouse1_idx` (`Warehouse_id` ASC),
  CONSTRAINT `fk_Employees_Warehouse1`
    FOREIGN KEY (`Warehouse_id`)
    REFERENCES `fresh_market`.`Warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Buyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Buyer` (
  `id` INT NOT NULL,
  `id_card_number` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idtable1_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Ordes_Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Ordes_Status` (
  `idOrdes_Status` INT NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`idOrdes_Status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Carrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Carrier` (
  `id` INT NOT NULL,
  `cid` VARCHAR(255) NOT NULL,
  `company_name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(255) NOT NULL,
  `Locaities_id` INT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_Carrier_Locaities1_idx` (`Locaities_id` ASC),
  CONSTRAINT `fk_Carrier_Locaities1`
    FOREIGN KEY (`Locaities_id`)
    REFERENCES `fresh_market`.`Locaities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Purchase_Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Purchase_Orders` (
  `id` INT NOT NULL,
  `order_number` VARCHAR(255) NULL,
  `order_date` DATETIME(6) NULL,
  `tracking_code` VARCHAR(255) NULL,
  `Warehouse_id` INT NOT NULL,
  `Carrier_id` INT NOT NULL,
  `Buyer_id` INT NOT NULL,
  `Ordes_Status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Purchase_Orders_Warehouse1_idx` (`Warehouse_id` ASC),
  INDEX `fk_Purchase_Orders_Carrier1_idx` (`Carrier_id` ASC),
  INDEX `fk_Purchase_Orders_Buyer1_idx` (`Buyer_id` ASC),
  INDEX `fk_Purchase_Orders_Ordes_Status1_idx` (`Ordes_Status_id` ASC),
  CONSTRAINT `fk_Purchase_Orders_Warehouse1`
    FOREIGN KEY (`Warehouse_id`)
    REFERENCES `fresh_market`.`Warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Orders_Carrier1`
    FOREIGN KEY (`Carrier_id`)
    REFERENCES `fresh_market`.`Carrier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Orders_Buyer1`
    FOREIGN KEY (`Buyer_id`)
    REFERENCES `fresh_market`.`Buyer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Orders_Ordes_Status1`
    FOREIGN KEY (`Ordes_Status_id`)
    REFERENCES `fresh_market`.`Ordes_Status` (`idOrdes_Status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Product_Batches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Product_Batches` (
  `id` INT NOT NULL,
  `batch_number` VARCHAR(255) NULL,
  `current_quantity` INT NULL,
  `current_temperature` DECIMAL(19,2) NULL,
  `due_data` DATETIME(6) NULL,
  `initial_quantity` INT NULL,
  `manufacturing_date` DATETIME(6) NULL,
  `manufacturing_hour` DATETIME(6) NULL,
  `minimum_temperature` DECIMAL(19,2) NULL,
  `Product_id1` INT NULL,
  `Section_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Product_Batches_Product1_idx` (`Product_id1` ASC),
  INDEX `fk_Product_Batches_Section1_idx` (`Section_id` ASC),
  CONSTRAINT `fk_Product_Batches_Product1`
    FOREIGN KEY (`Product_id1`)
    REFERENCES `fresh_market`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Batches_Section1`
    FOREIGN KEY (`Section_id`)
    REFERENCES `fresh_market`.`Section` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Inbound_Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Inbound_Orders` (
  `id` INT NOT NULL,
  `order_date` DATETIME(6) NULL,
  `order_number` VARCHAR(255) NULL,
  `Product_Batches_id` INT NOT NULL,
  `Warehouse_id` INT NOT NULL,
  `Employees_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Inbound_Orders_Product_Batches1_idx` (`Product_Batches_id` ASC),
  INDEX `fk_Inbound_Orders_Warehouse1_idx` (`Warehouse_id` ASC),
  INDEX `fk_Inbound_Orders_Employees1_idx` (`Employees_id` ASC),
  CONSTRAINT `fk_Inbound_Orders_Product_Batches1`
    FOREIGN KEY (`Product_Batches_id`)
    REFERENCES `fresh_market`.`Product_Batches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inbound_Orders_Warehouse1`
    FOREIGN KEY (`Warehouse_id`)
    REFERENCES `fresh_market`.`Warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inbound_Orders_Employees1`
    FOREIGN KEY (`Employees_id`)
    REFERENCES `fresh_market`.`Employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Product_Records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Product_Records` (
  `id` INT NOT NULL,
  `last_update_date` DATETIME(6) NULL,
  `purchase_code` DECIMAL(19,2) NULL,
  `sale_price` DECIMAL(19,2) NULL,
  `Product_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Product_Records_Product_idx` (`Product_id` ASC),
  CONSTRAINT `fk_Product_Records_Product`
    FOREIGN KEY (`Product_id`)
    REFERENCES `fresh_market`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Order_Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Order_Details` (
  `id` INT NOT NULL,
  `clean_liness_status` VARCHAR(255) NULL,
  `quantity` INT NULL,
  `temperature` DECIMAL(19,2) NULL,
  `Product_Records_id` INT NOT NULL,
  `Purchase_Orders_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Order_Details_Product_Records1_idx` (`Product_Records_id` ASC),
  INDEX `fk_Order_Details_Purchase_Orders1_idx` (`Purchase_Orders_id` ASC),
  CONSTRAINT `fk_Order_Details_Product_Records1`
    FOREIGN KEY (`Product_Records_id`)
    REFERENCES `fresh_market`.`Product_Records` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Details_Purchase_Orders1`
    FOREIGN KEY (`Purchase_Orders_id`)
    REFERENCES `fresh_market`.`Purchase_Orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Users` (
  `id` INT NOT NULL,
  `password` VARCHAR(255) NULL,
  `username` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`Rol` (
  `id` INT NOT NULL,
  `descriptiom` VARCHAR(255) NULL,
  `rol_name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`User_Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`User_Rol` (
  `Users_id` INT NOT NULL,
  `Rol_id` INT NOT NULL,
  INDEX `fk_User_Rol_Users1_idx` (`Users_id` ASC),
  INDEX `fk_User_Rol_Rol1_idx` (`Rol_id` ASC),
  CONSTRAINT `fk_User_Rol_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `fresh_market`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Rol_Rol1`
    FOREIGN KEY (`Rol_id`)
    REFERENCES `fresh_market`.`Rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
