-- MySQL Script generated by MySQL Workbench
-- Tue Jul  5 12:59:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fresh_market
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fresh_market
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fresh_market` DEFAULT CHARACTER SET utf8 ;
USE `fresh_market` ;

-- -----------------------------------------------------
-- Table `fresh_market`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`province` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `country_id` INT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_Provinces_Countries1_idx` (`country_id` ASC),
  CONSTRAINT `fk_Provinces_Countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `fresh_market`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`locality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`locality` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Locaities_Provinces1_idx` (`province_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Locaities_Provinces1`
    FOREIGN KEY (`province_id`)
    REFERENCES `fresh_market`.`province` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`seller` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cid` VARCHAR(255) NOT NULL,
  `company_name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(255) NOT NULL,
  `locality_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Seller_Locaities1_idx` (`locality_id` ASC),
  UNIQUE INDEX `cid_UNIQUE` (`cid` ASC),
  CONSTRAINT `fk_Seller_Locaities1`
    FOREIGN KEY (`locality_id`)
    REFERENCES `fresh_market`.`locality` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`product_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `expiration_rate` DECIMAL(19,2) NOT NULL,
  `freezing_rate` DECIMAL(19,2) NOT NULL,
  `heigth` DECIMAL(19,2) NOT NULL,
  `lenght` DECIMAL(19,2) NOT NULL,
  `net_weight` DECIMAL(19,2) NOT NULL,
  `product_code` VARCHAR(255) NOT NULL,
  `recommended_freezing_temperature` DECIMAL(19,2) NOT NULL,
  `width` DECIMAL(19,2) NOT NULL,
  `seller_id` INT NOT NULL,
  `product_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Product_Seller1_idx` (`seller_id` ASC),
  INDEX `fk_Product_Products_Types1_idx` (`product_type_id` ASC),
  UNIQUE INDEX `product_code_UNIQUE` (`product_code` ASC),
  CONSTRAINT `fk_Product_Seller1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `fresh_market`.`seller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Products_Types1`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `fresh_market`.`product_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`warehouse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(15) NOT NULL,
  `warehouse_code` VARCHAR(50) NOT NULL,
  `minimum_capacity` INT NOT NULL,
  `minimum_temperature` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `warehouse_code_UNIQUE` (`warehouse_code` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`section` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `section_number` VARCHAR(255) NOT NULL,
  `current_capacity` INT NOT NULL,
  `current_temperature` DECIMAL(19,2) NOT NULL,
  `maximum_capacity` INT NOT NULL,
  `minimum_capacity` INT NOT NULL,
  `minimum_temperature` DECIMAL(19,2) NOT NULL,
  `product_type_id` INT NOT NULL,
  `warehouse_id` INT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_Section_Products_Types1_idx` (`product_type_id` ASC),
  INDEX `fk_Section_Warehouse1_idx` (`warehouse_id` ASC),
  CONSTRAINT `fk_Section_Products_Types1`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `fresh_market`.`product_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Section_Warehouse1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `fresh_market`.`warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_card_number` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `warehouse_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Employees_Warehouse1_idx` (`warehouse_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Employees_Warehouse1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `fresh_market`.`warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`buyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`buyer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `card_number` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`order_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`carrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`carrier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cid` VARCHAR(255) NOT NULL,
  `company_name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(15) NOT NULL,
  `locality_id` INT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_Carrier_Locaities1_idx` (`locality_id` ASC),
  CONSTRAINT `fk_Carrier_Locaities1`
    FOREIGN KEY (`locality_id`)
    REFERENCES `fresh_market`.`locality` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`purchase_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`purchase_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_number` VARCHAR(255) NOT NULL,
  `order_date` DATETIME(6) NOT NULL,
  `tracking_code` VARCHAR(255) NOT NULL,
  `warehouse_id` INT NOT NULL,
  `carrier_id` INT NOT NULL,
  `buyer_id` INT NOT NULL,
  `order_status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Purchase_Orders_Warehouse1_idx` (`warehouse_id` ASC),
  INDEX `fk_Purchase_Orders_Carrier1_idx` (`carrier_id` ASC),
  INDEX `fk_Purchase_Orders_Buyer1_idx` (`buyer_id` ASC),
  INDEX `fk_Purchase_Orders_Ordes_Status1_idx` (`order_status_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Purchase_Orders_Warehouse1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `fresh_market`.`warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Orders_Carrier1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `fresh_market`.`carrier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Orders_Buyer1`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `fresh_market`.`buyer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Orders_Ordes_Status1`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `fresh_market`.`order_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`product_batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`product_batch` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `batch_number` VARCHAR(255) NOT NULL,
  `current_quantity` INT NOT NULL,
  `current_temperature` DECIMAL(19,2) NOT NULL,
  `due_date` DATETIME(6) NOT NULL,
  `initial_quantity` INT NOT NULL,
  `manufacturing_date` DATETIME(6) NOT NULL,
  `manufacturing_hour` INT NOT NULL,
  `minimum_temperature` DECIMAL(19,2) NOT NULL,
  `product_id` INT NOT NULL,
  `section_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Product_Batches_Product1_idx` (`product_id` ASC),
  INDEX `fk_Product_Batches_Section1_idx` (`section_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Product_Batches_Product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `fresh_market`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Batches_Section1`
    FOREIGN KEY (`section_id`)
    REFERENCES `fresh_market`.`section` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`inbound_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`inbound_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_date` DATETIME(6) NOT NULL,
  `order_number` VARCHAR(255) NOT NULL,
  `product_batch_id` INT NOT NULL,
  `warehouse_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Inbound_Orders_Product_Batches1_idx` (`product_batch_id` ASC),
  INDEX `fk_Inbound_Orders_Warehouse1_idx` (`warehouse_id` ASC),
  INDEX `fk_Inbound_Orders_Employees1_idx` (`employee_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Inbound_Orders_Product_Batches1`
    FOREIGN KEY (`product_batch_id`)
    REFERENCES `fresh_market`.`product_batch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inbound_Orders_Warehouse1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `fresh_market`.`warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inbound_Orders_Employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `fresh_market`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`product_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`product_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_update_date` DATETIME(6) NOT NULL,
  `purchase_code` DECIMAL(19,2) NOT NULL,
  `sale_price` DECIMAL(19,2) NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Product_Records_Product_idx` (`product_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Product_Records_Product`
    FOREIGN KEY (`product_id`)
    REFERENCES `fresh_market`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`order_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clean_lines_status` VARCHAR(255) NOT NULL,
  `quantity` INT NOT NULL,
  `temperature` DECIMAL(19,2) NOT NULL,
  `product_record_id` INT NOT NULL,
  `purchase_order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Order_Details_Product_Records1_idx` (`product_record_id` ASC),
  INDEX `fk_Order_Details_Purchase_Orders1_idx` (`purchase_order_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Order_Details_Product_Records1`
    FOREIGN KEY (`product_record_id`)
    REFERENCES `fresh_market`.`product_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Details_Purchase_Orders1`
    FOREIGN KEY (`purchase_order_id`)
    REFERENCES `fresh_market`.`purchase_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `rol_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fresh_market`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fresh_market`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_user_rol1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_rol1`
    FOREIGN KEY (`role_id`)
    REFERENCES `fresh_market`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
