// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	domain "github.com/natpapa17/MercadoFresco-ASociedadeGo/internal/sellers/domain"
	mock "github.com/stretchr/testify/mock"
)

// NRepository is an autogenerated mock type for the NRepository type
type NRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *NRepository) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *NRepository) GetAll() ([]domain.Seller, error) {
	ret := _m.Called()

	var r0 []domain.Seller
	if rf, ok := ret.Get(0).(func() []domain.Seller); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Seller)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *NRepository) GetById(id int) (domain.Seller, error) {
	ret := _m.Called(id)

	var r0 domain.Seller
	if rf, ok := ret.Get(0).(func(int) domain.Seller); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Seller)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: cid, companyName, address, telephone, localityId
func (_m *NRepository) Store(cid int, companyName string, address string, telephone string, localityId int) (domain.Seller, error) {
	ret := _m.Called(cid, companyName, address, telephone, localityId)

	var r0 domain.Seller
	if rf, ok := ret.Get(0).(func(int, string, string, string, int) domain.Seller); ok {
		r0 = rf(cid, companyName, address, telephone, localityId)
	} else {
		r0 = ret.Get(0).(domain.Seller)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string, string, string, int) error); ok {
		r1 = rf(cid, companyName, address, telephone, localityId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, cid, companyName, address, telephone, localityId
func (_m *NRepository) Update(id int, cid int, companyName string, address string, telephone string, localityId int) (domain.Seller, error) {
	ret := _m.Called(id, cid, companyName, address, telephone, localityId)

	var r0 domain.Seller
	if rf, ok := ret.Get(0).(func(int, int, string, string, string, int) domain.Seller); ok {
		r0 = rf(id, cid, companyName, address, telephone, localityId)
	} else {
		r0 = ret.Get(0).(domain.Seller)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, string, string, string, int) error); ok {
		r1 = rf(id, cid, companyName, address, telephone, localityId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewNRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewNRepository creates a new instance of NRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNRepository(t mockConstructorTestingTNewNRepository) *NRepository {
	mock := &NRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
