// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	products "github.com/natpapa17/MercadoFresco-ASociedadeGo/internal/products"
	records "github.com/natpapa17/MercadoFresco-ASociedadeGo/internal/records"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: last_update_date, purchase_price, sale_price, product_id
func (_m *Repository) Create(last_update_date string, purchase_price int, sale_price int, product_id int) (records.Records, error) {
	ret := _m.Called(last_update_date, purchase_price, sale_price, product_id)

	var r0 records.Records
	if rf, ok := ret.Get(0).(func(string, int, int, int) records.Records); ok {
		r0 = rf(last_update_date, purchase_price, sale_price, product_id)
	} else {
		r0 = ret.Get(0).(records.Records)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int, int, int) error); ok {
		r1 = rf(last_update_date, purchase_price, sale_price, product_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *Repository) GetAll() ([]records.Records, error) {
	ret := _m.Called()

	var r0 []records.Records
	if rf, ok := ret.Get(0).(func() []records.Records); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]records.Records)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *Repository) GetById(id int) (records.Records, error) {
	ret := _m.Called(id)

	var r0 records.Records
	if rf, ok := ret.Get(0).(func(int) records.Records); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(records.Records)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductId provides a mock function with given fields: product_id
func (_m *Repository) GetProductId(product_id int) (products.Product, error) {
	ret := _m.Called(product_id)

	var r0 products.Product
	if rf, ok := ret.Get(0).(func(int) products.Product); ok {
		r0 = rf(product_id)
	} else {
		r0 = ret.Get(0).(products.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(product_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
